//! SHA-3 (Keccak-f1600) absorb-sequence AIR.
//!
//! # Purpose
//!
//! The wrapper STARK has to verify the inner proof's Merkle paths and
//! re-derive its `pi_hash` Fiat-Shamir transcript.  Those operations
//! commit to SHA-3 hashes, so the wrapper AIR contains a SHA-3 sub-AIR.
//! This is the only place SHA-3-in-AIR is unavoidable; the dual-hash
//! architecture (paper §8) limits it to this subcircuit while the
//! wrapper's own internal Merkle uses Poseidon (cheap to express).
//!
//! # Keccak-f1600 structure (FIPS 202 §3)
//!
//! - **State**: 5×5×64 = 1 600 bits arranged as 25 64-bit lanes
//! - **Rounds**: 24, each composed of (θ, ρ, π, χ, ι)
//! - **θ**: XORs each lane with parity of two neighbouring columns
//! - **ρ**: rotates each lane by a fixed offset (see [`RHO_OFFSETS`])
//! - **π**: permutes lane positions (see [`PI_LANE_INDICES`])
//! - **χ**: non-linear `lane[x] ^= !lane[x+1] & lane[x+2]` per row
//! - **ι**: XORs round constant into lane (0,0) (see [`ROUND_CONSTANTS`])
//!
//! # AIR strategy
//!
//! Each Keccak round occupies a contiguous block of rows.  Within a
//! round, sub-steps are sequenced: one row range per (θ, ρ, π, χ, ι)
//! sub-step.  Bitwise operations are expressed by decomposing each
//! 64-bit lane into 64 boolean cells; the constraint set enforces:
//!
//! 1. **Booleanity**: every bit cell `b` satisfies `b · (b − 1) = 0`
//! 2. **XOR**: `c = a XOR b` ⇔ `c = a + b − 2·a·b` (boolean inputs)
//! 3. **AND**: `c = a AND b` ⇔ `c = a · b` (boolean inputs)
//! 4. **NOT**: `c = NOT a` ⇔ `c = 1 − a` (boolean input)
//!
//! Lane reconstruction at sub-step boundaries packs bits back into a
//! field element via `lane = Σ bᵢ · 2ⁱ` for `i ∈ [0..64)`.

/// SHA-3 variants the wrapper supports.  Maps to the inner proof's
/// FIPS-202 hash variant for the corresponding NIST PQ level.
///
/// Sponge parameters (FIPS 202 §6.1):
/// - SHA3-256: rate r = 1088 bits, capacity c = 512 bits, output 256 bits
/// - SHA3-384: rate r =  832 bits, capacity c = 768 bits, output 384 bits
/// - SHA3-512: rate r =  576 bits, capacity c =1024 bits, output 512 bits
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Sha3Variant {
    Sha3_256,
    Sha3_384,
    Sha3_512,
}

impl Sha3Variant {
    /// Sponge rate `r` in bits.  Block size is `r` bits = `r / 8` bytes.
    pub const fn rate_bits(self) -> usize {
        match self {
            Self::Sha3_256 => 1088,
            Self::Sha3_384 => 832,
            Self::Sha3_512 => 576,
        }
    }

    /// Sponge capacity `c` in bits.  `r + c = 1600` for all Keccak-f1600
    /// variants.  Capacity caps the effective collision entropy (paper
    /// Theorem 8 / Corollary 2).
    pub const fn capacity_bits(self) -> usize {
        1600 - self.rate_bits()
    }

    /// Output length in bits.
    pub const fn output_bits(self) -> usize {
        match self {
            Self::Sha3_256 => 256,
            Self::Sha3_384 => 384,
            Self::Sha3_512 => 512,
        }
    }

    /// Block size in bytes (= rate / 8).
    pub const fn block_bytes(self) -> usize {
        self.rate_bits() / 8
    }

    /// Output length in bytes.
    pub const fn output_bytes(self) -> usize {
        self.output_bits() / 8
    }

    /// The NIST PQ level this variant pairs with by default.
    /// L1 ↔ SHA3-256, L3 ↔ SHA3-384, L5 ↔ SHA3-512 (paper Table 2).
    pub const fn default_for_level(nist_level: u8) -> Self {
        match nist_level {
            1 => Self::Sha3_256,
            3 => Self::Sha3_384,
            5 => Self::Sha3_512,
            _ => panic!("Sha3Variant: unsupported NIST level"),
        }
    }
}

/// 24 round constants for Keccak-f1600 (FIPS 202 §3.2.5 Table 2).
/// Generated by the LFSR rc(t), applied to lane (0, 0) at each round's
/// ι step.
pub const ROUND_CONSTANTS: [u64; 24] = [
    0x0000_0000_0000_0001, 0x0000_0000_0000_8082,
    0x8000_0000_0000_808A, 0x8000_0000_8000_8000,
    0x0000_0000_0000_808B, 0x0000_0000_8000_0001,
    0x8000_0000_8000_8081, 0x8000_0000_0000_8009,
    0x0000_0000_0000_008A, 0x0000_0000_0000_0088,
    0x0000_0000_8000_8009, 0x0000_0000_8000_000A,
    0x0000_0000_8000_808B, 0x8000_0000_0000_008B,
    0x8000_0000_0000_8089, 0x8000_0000_0000_8003,
    0x8000_0000_0000_8002, 0x8000_0000_0000_0080,
    0x0000_0000_0000_800A, 0x8000_0000_8000_000A,
    0x8000_0000_8000_8081, 0x8000_0000_0000_8080,
    0x0000_0000_8000_0001, 0x8000_0000_8000_8008,
];

/// Per-lane rotation offsets used by the ρ step (FIPS 202 §3.2.2 Table 1).
/// Indexed as `RHO_OFFSETS[5*y + x]` where `(x, y) ∈ [0..5)²`.
/// Offsets are mod 64.
pub const RHO_OFFSETS: [u32; 25] = [
    // y = 0
     0,  1, 62, 28, 27,
    // y = 1
    36, 44,  6, 55, 20,
    // y = 2
     3, 10, 43, 25, 39,
    // y = 3
    41, 45, 15, 21,  8,
    // y = 4
    18,  2, 61, 56, 14,
];

/// Lane index permutation used by the π step (FIPS 202 §3.2.3).
/// After π, lane at position `(x, y)` comes from the lane previously
/// at position `(x + 3·y mod 5, x)`.  We pre-compute the source index
/// for each destination as `5·y + x → 5·x + (x + 3·y mod 5)`.
pub const PI_LANE_INDICES: [usize; 25] = {
    let mut out = [0usize; 25];
    let mut i = 0;
    while i < 25 {
        let x = i % 5;
        let y = i / 5;
        // π maps (x, y) → (y, 2x + 3y mod 5).
        // Equivalently, destination (x', y') reads from source
        // (x_src, y_src) = (y', x'+3y' mod 5).
        let x_src = y;
        let y_src = (2 * x + 3 * y) % 5;
        out[5 * y_src + x_src] = i;  // canonical π destination → source mapping
        i += 1;
    }
    out
};

/// Sub-steps of one Keccak round, in execution order within a row range.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RoundStep {
    /// Compute column parities `C[x] = ⊕_y A[x, y]` and apply
    /// `A[x, y] ⊕= C[x-1] ⊕ ROTL1(C[x+1])`.
    Theta,
    /// Per-lane rotation by [`RHO_OFFSETS`].
    Rho,
    /// Lane index permutation by [`PI_LANE_INDICES`].
    Pi,
    /// Non-linear `A[x, y] ⊕= !A[x+1, y] & A[x+2, y]` per row.
    Chi,
    /// XOR round constant into lane (0, 0).
    Iota,
}

impl RoundStep {
    pub const ALL: [RoundStep; 5] = [
        RoundStep::Theta, RoundStep::Rho, RoundStep::Pi,
        RoundStep::Chi, RoundStep::Iota,
    ];
}

/// Native Keccak-f1600 state: 25 lanes of 64 bits.  Used as the
/// reference oracle for AIR-side correctness checks during testing.
pub type KeccakState = [u64; 25];

/// Column layout for the SHA-3 absorb sub-AIR.
///
/// Within each round-row block, columns are organised as:
/// - 25 lanes × 64 boolean cells = 1 600 bit cells (state representation)
/// - 25 column-parity cells (θ helper)
/// - 25 rotated-lane cells (ρ output)
/// - 25 permuted-lane cells (π output)
/// - 25 χ-output cells (one per lane after non-linear step)
/// - 1 round-constant cell (ι input from [`ROUND_CONSTANTS`])
/// - 5 sub-step selector cells (one per [`RoundStep`])
#[derive(Clone, Debug)]
pub struct AbsorbAirLayout {
    pub variant: Sha3Variant,
    /// Trace width: per-step bit-decomposed cells + helpers + selectors.
    pub width: usize,
    /// Rows per single Keccak-f1600 permutation (= 24 rounds × 5 steps).
    pub rows_per_permutation: usize,
    /// Rows for a complete absorb of one input block (= 1 absorb XOR + 1 permutation).
    pub rows_per_absorb_block: usize,
    /// Number of input blocks the layout is sized for (caller-provided).
    pub n_blocks: usize,
}

impl AbsorbAirLayout {
    /// Build a layout sized for absorbing `n_blocks` input blocks using
    /// `variant`.  Production blocks pack `variant.block_bytes()` bytes
    /// each before zero-padding the final block.
    pub fn new(variant: Sha3Variant, n_blocks: usize) -> Self {
        let rows_per_permutation = 24 * RoundStep::ALL.len();  // 24 × 5 = 120
        let rows_per_absorb_block = rows_per_permutation + 1;   // +1 for the XOR-in row
        // Width: 1600 state bits + 25 parity + 25 rotated + 25 permuted
        // + 25 chi-out + 1 round constant + 5 selectors.  Each bit is a
        // boolean cell, parity/rotated/permuted/chi cells are 64-bit
        // lanes encoded as a single field element each.
        let width = 1600 /* state bits */
                  + 25 * 4 /* parity + rotated + permuted + chi-out lanes */
                  + 1     /* round constant lane */
                  + 5;    /* sub-step selectors */
        Self { variant, width, rows_per_permutation, rows_per_absorb_block, n_blocks }
    }

    /// Total rows required for the absorb sequence (sum across blocks).
    pub fn total_rows(&self) -> usize {
        self.rows_per_absorb_block * self.n_blocks
    }
}

// ─── Native reference (used by tests + future AIR oracle) ────────────
//
// Implementation derives directly from FIPS 202 §3.2.  Each sub-step
// uses ONLY this module's constants tables, so the AIR's behaviour
// can be compared against this code without any dependency on
// rustcrypto.  rustcrypto is used in tests as an independent oracle.

/// Native Keccak-f1600 permutation — reference implementation that the
/// AIR's constraints will be validated against.  In-place transformation
/// of the 25-lane state.
///
/// Implements FIPS 202 §3.2 directly using [`RHO_OFFSETS`],
/// [`PI_LANE_INDICES`], and [`ROUND_CONSTANTS`].  No external crypto
/// dependencies — that's the whole point of having this as a reference.
pub fn keccak_f1600(state: &mut KeccakState) {
    for round in 0..24 {
        // θ: column parities + diffuse
        let mut c = [0u64; 5];
        for x in 0..5 {
            c[x] = state[x] ^ state[x + 5] ^ state[x + 10] ^ state[x + 15] ^ state[x + 20];
        }
        let mut d = [0u64; 5];
        for x in 0..5 {
            d[x] = c[(x + 4) % 5] ^ c[(x + 1) % 5].rotate_left(1);
        }
        for x in 0..5 {
            for y in 0..5 {
                state[5 * y + x] ^= d[x];
            }
        }

        // ρ + π fused (write into a fresh array, then copy back).
        // π maps lane (x, y) → (y, 2x + 3y mod 5); we precomputed
        // the destination-source mapping in PI_LANE_INDICES, but
        // for clarity we recompute here.
        let mut b = [0u64; 25];
        for x in 0..5 {
            for y in 0..5 {
                let src = 5 * y + x;
                let dst = 5 * ((2 * x + 3 * y) % 5) + y;
                b[dst] = state[src].rotate_left(RHO_OFFSETS[src]);
            }
        }

        // χ: non-linear A[x,y] = B[x,y] ^ ((¬B[x+1,y]) & B[x+2,y])
        for y in 0..5 {
            let row = [
                b[5 * y    ], b[5 * y + 1], b[5 * y + 2],
                b[5 * y + 3], b[5 * y + 4],
            ];
            for x in 0..5 {
                state[5 * y + x] = row[x] ^ ((!row[(x + 1) % 5]) & row[(x + 2) % 5]);
            }
        }

        // ι: XOR round constant into lane (0, 0)
        state[0] ^= ROUND_CONSTANTS[round];
    }
}

/// Absorb a single rate-sized block into the sponge state.  XORs the
/// first `variant.block_bytes()` bytes of `block` into the rate region
/// of `state` (lane 0 = bytes 0..8 little-endian, etc.), then applies
/// the permutation.
///
/// Caller must ensure `block.len() == variant.block_bytes()`.
pub fn absorb_block(state: &mut KeccakState, block: &[u8], variant: Sha3Variant) {
    assert_eq!(block.len(), variant.block_bytes(),
        "absorb_block: block size must equal variant.block_bytes()");
    // Number of lanes in the rate region.
    let rate_lanes = variant.rate_bits() / 64;
    for i in 0..rate_lanes {
        let mut lane = 0u64;
        for j in 0..8 {
            lane |= (block[8 * i + j] as u64) << (8 * j);
        }
        state[i] ^= lane;
    }
    keccak_f1600(state);
}

/// Squeeze the fixed-output digest from the sponge state.  Returns
/// `variant.output_bytes()` bytes.  All SHA-3 variants have
/// `output_bits ≤ rate_bits`, so no further permutation is needed.
pub fn squeeze(state: &KeccakState, variant: Sha3Variant) -> Vec<u8> {
    let out_bytes = variant.output_bytes();
    debug_assert!(variant.output_bits() <= variant.rate_bits(),
        "single-squeeze invariant must hold for fixed-output SHA-3");
    let mut out = Vec::with_capacity(out_bytes);
    let full_lanes = out_bytes / 8;
    for i in 0..full_lanes {
        out.extend_from_slice(&state[i].to_le_bytes());
    }
    let tail = out_bytes - 8 * full_lanes;
    if tail > 0 {
        let bytes = state[full_lanes].to_le_bytes();
        out.extend_from_slice(&bytes[..tail]);
    }
    out
}

/// End-to-end SHA-3 hash with FIPS 202 §B.2 domain-separated padding
/// (suffix `01` || pad10*1).  Equivalent to rustcrypto's `Sha3_N` for
/// the matching variant — verified by the test suite below.
pub fn hash(variant: Sha3Variant, input: &[u8]) -> Vec<u8> {
    let block_len = variant.block_bytes();
    let mut state: KeccakState = [0; 25];

    // Absorb all full blocks.
    let mut offset = 0;
    while offset + block_len <= input.len() {
        absorb_block(&mut state, &input[offset..offset + block_len], variant);
        offset += block_len;
    }

    // Build the final padded block.  SHA-3 domain separator byte is
    // 0x06 (= `0b00000110`: the `01` suffix in little-endian bit
    // order followed by the leading `1` of pad10*1).  The trailing
    // `1` of pad10*1 is the MSB of the last byte of the block.
    let mut last = vec![0u8; block_len];
    let tail = &input[offset..];
    last[..tail.len()].copy_from_slice(tail);
    last[tail.len()] = 0x06;
    last[block_len - 1] |= 0x80;
    absorb_block(&mut state, &last, variant);

    squeeze(&state, variant)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sha3_variant_sponge_invariant() {
        for v in [Sha3Variant::Sha3_256, Sha3Variant::Sha3_384, Sha3Variant::Sha3_512] {
            // FIPS 202 sponge invariant: r + c = 1600.
            assert_eq!(v.rate_bits() + v.capacity_bits(), 1600);
            // Output ≤ rate (otherwise extra squeeze rounds needed).
            assert!(v.output_bits() <= v.rate_bits());
            // Block size is byte-aligned.
            assert_eq!(v.rate_bits() % 8, 0);
        }
    }

    #[test]
    fn sha3_variant_specific_values() {
        // FIPS 202 §6.1 Table 3.
        assert_eq!(Sha3Variant::Sha3_256.rate_bits(),  1088);
        assert_eq!(Sha3Variant::Sha3_256.capacity_bits(), 512);
        assert_eq!(Sha3Variant::Sha3_256.output_bytes(), 32);
        assert_eq!(Sha3Variant::Sha3_256.block_bytes(),  136);

        assert_eq!(Sha3Variant::Sha3_384.rate_bits(),   832);
        assert_eq!(Sha3Variant::Sha3_384.capacity_bits(), 768);
        assert_eq!(Sha3Variant::Sha3_384.output_bytes(), 48);
        assert_eq!(Sha3Variant::Sha3_384.block_bytes(),  104);

        assert_eq!(Sha3Variant::Sha3_512.rate_bits(),   576);
        assert_eq!(Sha3Variant::Sha3_512.capacity_bits(), 1024);
        assert_eq!(Sha3Variant::Sha3_512.output_bytes(), 64);
        assert_eq!(Sha3Variant::Sha3_512.block_bytes(),  72);
    }

    #[test]
    fn sha3_variant_default_for_level() {
        assert_eq!(Sha3Variant::default_for_level(1), Sha3Variant::Sha3_256);
        assert_eq!(Sha3Variant::default_for_level(3), Sha3Variant::Sha3_384);
        assert_eq!(Sha3Variant::default_for_level(5), Sha3Variant::Sha3_512);
    }

    #[test]
    fn round_constants_count_and_shape() {
        assert_eq!(ROUND_CONSTANTS.len(), 24);
        // First constant must be 1 (lowest LFSR output before stepping).
        assert_eq!(ROUND_CONSTANTS[0], 0x0000_0000_0000_0001);
        // ι output must fit in 64 bits — vacuous for u64 but confirms type.
        for rc in ROUND_CONSTANTS {
            assert!(rc <= u64::MAX);
        }
    }

    #[test]
    fn rho_offsets_well_formed() {
        // FIPS 202 §3.2.2 Table 1: exactly one offset is 0 (lane (0, 0));
        // remaining 24 offsets are distinct mod 64.
        assert_eq!(RHO_OFFSETS.len(), 25);
        assert_eq!(RHO_OFFSETS[0], 0);
        let mut nonzero: Vec<u32> = RHO_OFFSETS.iter().filter(|&&o| o != 0).copied().collect();
        nonzero.sort();
        nonzero.dedup();
        assert_eq!(nonzero.len(), 24, "ρ offsets must be 24 distinct non-zero values");
        // All offsets are < 64.
        assert!(RHO_OFFSETS.iter().all(|&o| o < 64));
    }

    #[test]
    fn pi_lane_indices_is_permutation() {
        // π is a permutation of {0..25}.
        assert_eq!(PI_LANE_INDICES.len(), 25);
        let mut sorted: Vec<usize> = PI_LANE_INDICES.to_vec();
        sorted.sort();
        for i in 0..25 {
            assert_eq!(sorted[i], i, "PI_LANE_INDICES is not a permutation");
        }
    }

    #[test]
    fn round_step_count() {
        assert_eq!(RoundStep::ALL.len(), 5);
    }

    #[test]
    fn absorb_layout_row_budget() {
        let l = AbsorbAirLayout::new(Sha3Variant::Sha3_384, 4);
        assert_eq!(l.rows_per_permutation, 120);  // 24 × 5
        assert_eq!(l.rows_per_absorb_block, 121); // 120 + XOR row
        assert_eq!(l.total_rows(), 121 * 4);
        // Width sanity: 1600 state bits + 4×25 helper lanes + 1 RC + 5 selectors.
        assert_eq!(l.width, 1600 + 100 + 1 + 5);
    }

    #[test]
    fn absorb_layout_scales_linearly_with_blocks() {
        let l1 = AbsorbAirLayout::new(Sha3Variant::Sha3_256, 1);
        let l4 = AbsorbAirLayout::new(Sha3Variant::Sha3_256, 4);
        assert_eq!(l4.total_rows(), 4 * l1.total_rows());
        // Width is independent of block count.
        assert_eq!(l4.width, l1.width);
    }

    #[test]
    #[should_panic(expected = "unsupported NIST level")]
    fn sha3_variant_rejects_invalid_level() {
        let _ = Sha3Variant::default_for_level(2);
    }

    // ─── NIST CAVS test vectors (FIPS 202) ──────────────────────────
    //
    // These vectors are *external* references — they don't come from
    // our own SHA-3 code or rustcrypto.  If the native Keccak diverges
    // from FIPS 202, these tests catch it before the AIR is built on
    // top.  See `feedback_test_primitive_against_external_ref.md`.

    fn hex_to_bytes(s: &str) -> Vec<u8> {
        (0..s.len()).step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
            .collect()
    }

    #[test]
    fn sha3_256_empty_input_matches_fips_vector() {
        let expected = hex_to_bytes(
            "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a");
        assert_eq!(hash(Sha3Variant::Sha3_256, b""), expected);
    }

    #[test]
    fn sha3_256_abc_matches_fips_vector() {
        let expected = hex_to_bytes(
            "3a985da74fe225b2045c172d6bd390bd855f086e3e9d525b46bfe24511431532");
        assert_eq!(hash(Sha3Variant::Sha3_256, b"abc"), expected);
    }

    #[test]
    fn sha3_384_empty_input_matches_fips_vector() {
        let expected = hex_to_bytes(
            "0c63a75b845e4f7d01107d852e4c2485c51a50aaaa94fc61995e71bbee983a2ac3713831264adb47fb6bd1e058d5f004");
        assert_eq!(hash(Sha3Variant::Sha3_384, b""), expected);
    }

    #[test]
    fn sha3_384_abc_matches_fips_vector() {
        let expected = hex_to_bytes(
            "ec01498288516fc926459f58e2c6ad8df9b473cb0fc08c2596da7cf0e49be4b298d88cea927ac7f539f1edf228376d25");
        assert_eq!(hash(Sha3Variant::Sha3_384, b"abc"), expected);
    }

    #[test]
    fn sha3_512_empty_input_matches_fips_vector() {
        let expected = hex_to_bytes(
            "a69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26");
        assert_eq!(hash(Sha3Variant::Sha3_512, b""), expected);
    }

    #[test]
    fn sha3_512_abc_matches_fips_vector() {
        let expected = hex_to_bytes(
            "b751850b1a57168a5693cd924b6b096e08f621827444f70d884f5d0240d2712e10e116e9192af3c91a7ec57647e3934057340b4cf408d5a56592f8274eec53f0");
        assert_eq!(hash(Sha3Variant::Sha3_512, b"abc"), expected);
    }

    // ─── Independent cross-check against rustcrypto ─────────────────
    //
    // The above FIPS vectors cover empty + "abc" inputs.  These tests
    // use rustcrypto's `sha3` crate as an independent oracle for
    // longer / random inputs that span multiple absorb blocks.

    fn rustcrypto_sha3_256(input: &[u8]) -> Vec<u8> {
        use ::sha3::Digest;
        let mut h = ::sha3::Sha3_256::new();
        h.update(input);
        h.finalize().to_vec()
    }

    fn rustcrypto_sha3_384(input: &[u8]) -> Vec<u8> {
        use ::sha3::Digest;
        let mut h = ::sha3::Sha3_384::new();
        h.update(input);
        h.finalize().to_vec()
    }

    fn rustcrypto_sha3_512(input: &[u8]) -> Vec<u8> {
        use ::sha3::Digest;
        let mut h = ::sha3::Sha3_512::new();
        h.update(input);
        h.finalize().to_vec()
    }

    #[test]
    fn cross_check_sha3_256_multi_block() {
        // 200 bytes spans multiple absorb blocks for all variants.
        let input = vec![0xA5u8; 200];
        assert_eq!(hash(Sha3Variant::Sha3_256, &input), rustcrypto_sha3_256(&input));
    }

    #[test]
    fn cross_check_sha3_384_multi_block() {
        let input = vec![0xA5u8; 200];
        assert_eq!(hash(Sha3Variant::Sha3_384, &input), rustcrypto_sha3_384(&input));
    }

    #[test]
    fn cross_check_sha3_512_multi_block() {
        // 200 bytes / 72-byte rate = 2.78 blocks → 3 absorb iterations.
        let input = vec![0xA5u8; 200];
        assert_eq!(hash(Sha3Variant::Sha3_512, &input), rustcrypto_sha3_512(&input));
    }

    #[test]
    fn cross_check_block_size_boundaries() {
        // Edge cases: input length exactly equal to block size, and
        // block_size + 1 (forces extra padding block).
        for variant in [Sha3Variant::Sha3_256, Sha3Variant::Sha3_384, Sha3Variant::Sha3_512] {
            let bs = variant.block_bytes();
            for len in [0usize, 1, bs - 1, bs, bs + 1, 2 * bs - 1, 2 * bs, 2 * bs + 1] {
                let input: Vec<u8> = (0..len).map(|i| (i % 256) as u8).collect();
                let ours = hash(variant, &input);
                let theirs = match variant {
                    Sha3Variant::Sha3_256 => rustcrypto_sha3_256(&input),
                    Sha3Variant::Sha3_384 => rustcrypto_sha3_384(&input),
                    Sha3Variant::Sha3_512 => rustcrypto_sha3_512(&input),
                };
                assert_eq!(ours, theirs,
                    "variant={variant:?} len={len} disagrees with rustcrypto");
            }
        }
    }

    #[test]
    fn permutation_changes_state() {
        // After one Keccak-f1600, the zero state must no longer be zero.
        let mut s: KeccakState = [0; 25];
        keccak_f1600(&mut s);
        // The first ι constant is 0x01, so state[0] = ... after
        // diffusion via χ.  Whatever the exact value, it must differ
        // from zero in at least one lane.
        assert!(s.iter().any(|&l| l != 0));
    }
}
