//! SHA-3 (Keccak-f1600) absorb-sequence AIR.
//!
//! # Purpose
//!
//! The wrapper STARK has to verify the inner proof's Merkle paths and
//! re-derive its `pi_hash` Fiat-Shamir transcript.  Those operations
//! commit to SHA-3 hashes, so the wrapper AIR contains a SHA-3 sub-AIR.
//! This is the only place SHA-3-in-AIR is unavoidable; the dual-hash
//! architecture (paper §8) limits it to this subcircuit while the
//! wrapper's own internal Merkle uses Poseidon (cheap to express).
//!
//! # Keccak-f1600 structure (FIPS 202 §3)
//!
//! - **State**: 5×5×64 = 1 600 bits arranged as 25 64-bit lanes
//! - **Rounds**: 24, each composed of (θ, ρ, π, χ, ι)
//! - **θ**: XORs each lane with parity of two neighbouring columns
//! - **ρ**: rotates each lane by a fixed offset (see [`RHO_OFFSETS`])
//! - **π**: permutes lane positions (see [`PI_LANE_INDICES`])
//! - **χ**: non-linear `lane[x] ^= !lane[x+1] & lane[x+2]` per row
//! - **ι**: XORs round constant into lane (0,0) (see [`ROUND_CONSTANTS`])
//!
//! # AIR strategy
//!
//! Each Keccak round occupies a contiguous block of rows.  Within a
//! round, sub-steps are sequenced: one row range per (θ, ρ, π, χ, ι)
//! sub-step.  Bitwise operations are expressed by decomposing each
//! 64-bit lane into 64 boolean cells; the constraint set enforces:
//!
//! 1. **Booleanity**: every bit cell `b` satisfies `b · (b − 1) = 0`
//! 2. **XOR**: `c = a XOR b` ⇔ `c = a + b − 2·a·b` (boolean inputs)
//! 3. **AND**: `c = a AND b` ⇔ `c = a · b` (boolean inputs)
//! 4. **NOT**: `c = NOT a` ⇔ `c = 1 − a` (boolean input)
//!
//! Lane reconstruction at sub-step boundaries packs bits back into a
//! field element via `lane = Σ bᵢ · 2ⁱ` for `i ∈ [0..64)`.

/// SHA-3 variants the wrapper supports.  Maps to the inner proof's
/// FIPS-202 hash variant for the corresponding NIST PQ level.
///
/// Sponge parameters (FIPS 202 §6.1):
/// - SHA3-256: rate r = 1088 bits, capacity c = 512 bits, output 256 bits
/// - SHA3-384: rate r =  832 bits, capacity c = 768 bits, output 384 bits
/// - SHA3-512: rate r =  576 bits, capacity c =1024 bits, output 512 bits
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Sha3Variant {
    Sha3_256,
    Sha3_384,
    Sha3_512,
}

impl Sha3Variant {
    /// Sponge rate `r` in bits.  Block size is `r` bits = `r / 8` bytes.
    pub const fn rate_bits(self) -> usize {
        match self {
            Self::Sha3_256 => 1088,
            Self::Sha3_384 => 832,
            Self::Sha3_512 => 576,
        }
    }

    /// Sponge capacity `c` in bits.  `r + c = 1600` for all Keccak-f1600
    /// variants.  Capacity caps the effective collision entropy (paper
    /// Theorem 8 / Corollary 2).
    pub const fn capacity_bits(self) -> usize {
        1600 - self.rate_bits()
    }

    /// Output length in bits.
    pub const fn output_bits(self) -> usize {
        match self {
            Self::Sha3_256 => 256,
            Self::Sha3_384 => 384,
            Self::Sha3_512 => 512,
        }
    }

    /// Block size in bytes (= rate / 8).
    pub const fn block_bytes(self) -> usize {
        self.rate_bits() / 8
    }

    /// Output length in bytes.
    pub const fn output_bytes(self) -> usize {
        self.output_bits() / 8
    }

    /// The NIST PQ level this variant pairs with by default.
    /// L1 ↔ SHA3-256, L3 ↔ SHA3-384, L5 ↔ SHA3-512 (paper Table 2).
    pub const fn default_for_level(nist_level: u8) -> Self {
        match nist_level {
            1 => Self::Sha3_256,
            3 => Self::Sha3_384,
            5 => Self::Sha3_512,
            _ => panic!("Sha3Variant: unsupported NIST level"),
        }
    }
}

/// 24 round constants for Keccak-f1600 (FIPS 202 §3.2.5 Table 2).
/// Generated by the LFSR rc(t), applied to lane (0, 0) at each round's
/// ι step.
pub const ROUND_CONSTANTS: [u64; 24] = [
    0x0000_0000_0000_0001, 0x0000_0000_0000_8082,
    0x8000_0000_0000_808A, 0x8000_0000_8000_8000,
    0x0000_0000_0000_808B, 0x0000_0000_8000_0001,
    0x8000_0000_8000_8081, 0x8000_0000_0000_8009,
    0x0000_0000_0000_008A, 0x0000_0000_0000_0088,
    0x0000_0000_8000_8009, 0x0000_0000_8000_000A,
    0x0000_0000_8000_808B, 0x8000_0000_0000_008B,
    0x8000_0000_0000_8089, 0x8000_0000_0000_8003,
    0x8000_0000_0000_8002, 0x8000_0000_0000_0080,
    0x0000_0000_0000_800A, 0x8000_0000_8000_000A,
    0x8000_0000_8000_8081, 0x8000_0000_0000_8080,
    0x0000_0000_8000_0001, 0x8000_0000_8000_8008,
];

/// Per-lane rotation offsets used by the ρ step (FIPS 202 §3.2.2 Table 1).
/// Indexed as `RHO_OFFSETS[5*y + x]` where `(x, y) ∈ [0..5)²`.
/// Offsets are mod 64.
pub const RHO_OFFSETS: [u32; 25] = [
    // y = 0
     0,  1, 62, 28, 27,
    // y = 1
    36, 44,  6, 55, 20,
    // y = 2
     3, 10, 43, 25, 39,
    // y = 3
    41, 45, 15, 21,  8,
    // y = 4
    18,  2, 61, 56, 14,
];

/// Lane index permutation used by the π step (FIPS 202 §3.2.3).
/// After π, lane at position `(x, y)` comes from the lane previously
/// at position `(x + 3·y mod 5, x)`.  We pre-compute the source index
/// for each destination as `5·y + x → 5·x + (x + 3·y mod 5)`.
pub const PI_LANE_INDICES: [usize; 25] = {
    let mut out = [0usize; 25];
    let mut i = 0;
    while i < 25 {
        let x = i % 5;
        let y = i / 5;
        // π maps (x, y) → (y, 2x + 3y mod 5).
        // Equivalently, destination (x', y') reads from source
        // (x_src, y_src) = (y', x'+3y' mod 5).
        let x_src = y;
        let y_src = (2 * x + 3 * y) % 5;
        out[5 * y_src + x_src] = i;  // canonical π destination → source mapping
        i += 1;
    }
    out
};

/// Sub-steps of one Keccak round, in execution order within a row range.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RoundStep {
    /// Compute column parities `C[x] = ⊕_y A[x, y]` and apply
    /// `A[x, y] ⊕= C[x-1] ⊕ ROTL1(C[x+1])`.
    Theta,
    /// Per-lane rotation by [`RHO_OFFSETS`].
    Rho,
    /// Lane index permutation by [`PI_LANE_INDICES`].
    Pi,
    /// Non-linear `A[x, y] ⊕= !A[x+1, y] & A[x+2, y]` per row.
    Chi,
    /// XOR round constant into lane (0, 0).
    Iota,
}

impl RoundStep {
    pub const ALL: [RoundStep; 5] = [
        RoundStep::Theta, RoundStep::Rho, RoundStep::Pi,
        RoundStep::Chi, RoundStep::Iota,
    ];
}

/// Native Keccak-f1600 state: 25 lanes of 64 bits.  Used as the
/// reference oracle for AIR-side correctness checks during testing.
pub type KeccakState = [u64; 25];

/// Column layout for the SHA-3 absorb sub-AIR.
///
/// Within each round-row block, columns are organised as:
/// - 25 lanes × 64 boolean cells = 1 600 bit cells (state representation)
/// - 25 column-parity cells (θ helper)
/// - 25 rotated-lane cells (ρ output)
/// - 25 permuted-lane cells (π output)
/// - 25 χ-output cells (one per lane after non-linear step)
/// - 1 round-constant cell (ι input from [`ROUND_CONSTANTS`])
/// - 5 sub-step selector cells (one per [`RoundStep`])
#[derive(Clone, Debug)]
pub struct AbsorbAirLayout {
    pub variant: Sha3Variant,
    /// Trace width: per-step bit-decomposed cells + helpers + selectors.
    pub width: usize,
    /// Rows per single Keccak-f1600 permutation (= 24 rounds × 5 steps).
    pub rows_per_permutation: usize,
    /// Rows for a complete absorb of one input block (= 1 absorb XOR + 1 permutation).
    pub rows_per_absorb_block: usize,
    /// Number of input blocks the layout is sized for (caller-provided).
    pub n_blocks: usize,
}

impl AbsorbAirLayout {
    /// Build a layout sized for absorbing `n_blocks` input blocks using
    /// `variant`.  Production blocks pack `variant.block_bytes()` bytes
    /// each before zero-padding the final block.
    pub fn new(variant: Sha3Variant, n_blocks: usize) -> Self {
        let rows_per_permutation = 24 * RoundStep::ALL.len();  // 24 × 5 = 120
        let rows_per_absorb_block = rows_per_permutation + 1;   // +1 for the XOR-in row
        // Width: 1600 state bits + 25 parity + 25 rotated + 25 permuted
        // + 25 chi-out + 1 round constant + 5 selectors.  Each bit is a
        // boolean cell, parity/rotated/permuted/chi cells are 64-bit
        // lanes encoded as a single field element each.
        let width = 1600 /* state bits */
                  + 25 * 4 /* parity + rotated + permuted + chi-out lanes */
                  + 1     /* round constant lane */
                  + 5;    /* sub-step selectors */
        Self { variant, width, rows_per_permutation, rows_per_absorb_block, n_blocks }
    }

    /// Total rows required for the absorb sequence (sum across blocks).
    pub fn total_rows(&self) -> usize {
        self.rows_per_absorb_block * self.n_blocks
    }
}

// ─── Native reference (used by tests + future AIR oracle) ────────────

/// Native Keccak-f1600 permutation — reference implementation used to
/// validate the AIR's constraints during testing.  Stub: zeroes the
/// state and panics on call, so accidental "works because reference"
/// passes can't sneak through.  Real impl lands in a subsequent commit.
pub fn keccak_f1600(_state: &mut KeccakState) {
    panic!("keccak_f1600: reference implementation not yet wired");
}

/// Absorb a single block into the sponge state.  Stub.
pub fn absorb_block(_state: &mut KeccakState, _block: &[u8], _variant: Sha3Variant) {
    panic!("absorb_block: not yet wired");
}

/// Squeeze the output digest from the sponge state.  Stub.
pub fn squeeze(_state: &KeccakState, _variant: Sha3Variant) -> Vec<u8> {
    panic!("squeeze: not yet wired");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sha3_variant_sponge_invariant() {
        for v in [Sha3Variant::Sha3_256, Sha3Variant::Sha3_384, Sha3Variant::Sha3_512] {
            // FIPS 202 sponge invariant: r + c = 1600.
            assert_eq!(v.rate_bits() + v.capacity_bits(), 1600);
            // Output ≤ rate (otherwise extra squeeze rounds needed).
            assert!(v.output_bits() <= v.rate_bits());
            // Block size is byte-aligned.
            assert_eq!(v.rate_bits() % 8, 0);
        }
    }

    #[test]
    fn sha3_variant_specific_values() {
        // FIPS 202 §6.1 Table 3.
        assert_eq!(Sha3Variant::Sha3_256.rate_bits(),  1088);
        assert_eq!(Sha3Variant::Sha3_256.capacity_bits(), 512);
        assert_eq!(Sha3Variant::Sha3_256.output_bytes(), 32);
        assert_eq!(Sha3Variant::Sha3_256.block_bytes(),  136);

        assert_eq!(Sha3Variant::Sha3_384.rate_bits(),   832);
        assert_eq!(Sha3Variant::Sha3_384.capacity_bits(), 768);
        assert_eq!(Sha3Variant::Sha3_384.output_bytes(), 48);
        assert_eq!(Sha3Variant::Sha3_384.block_bytes(),  104);

        assert_eq!(Sha3Variant::Sha3_512.rate_bits(),   576);
        assert_eq!(Sha3Variant::Sha3_512.capacity_bits(), 1024);
        assert_eq!(Sha3Variant::Sha3_512.output_bytes(), 64);
        assert_eq!(Sha3Variant::Sha3_512.block_bytes(),  72);
    }

    #[test]
    fn sha3_variant_default_for_level() {
        assert_eq!(Sha3Variant::default_for_level(1), Sha3Variant::Sha3_256);
        assert_eq!(Sha3Variant::default_for_level(3), Sha3Variant::Sha3_384);
        assert_eq!(Sha3Variant::default_for_level(5), Sha3Variant::Sha3_512);
    }

    #[test]
    fn round_constants_count_and_shape() {
        assert_eq!(ROUND_CONSTANTS.len(), 24);
        // First constant must be 1 (lowest LFSR output before stepping).
        assert_eq!(ROUND_CONSTANTS[0], 0x0000_0000_0000_0001);
        // ι output must fit in 64 bits — vacuous for u64 but confirms type.
        for rc in ROUND_CONSTANTS {
            assert!(rc <= u64::MAX);
        }
    }

    #[test]
    fn rho_offsets_well_formed() {
        // FIPS 202 §3.2.2 Table 1: exactly one offset is 0 (lane (0, 0));
        // remaining 24 offsets are distinct mod 64.
        assert_eq!(RHO_OFFSETS.len(), 25);
        assert_eq!(RHO_OFFSETS[0], 0);
        let mut nonzero: Vec<u32> = RHO_OFFSETS.iter().filter(|&&o| o != 0).copied().collect();
        nonzero.sort();
        nonzero.dedup();
        assert_eq!(nonzero.len(), 24, "ρ offsets must be 24 distinct non-zero values");
        // All offsets are < 64.
        assert!(RHO_OFFSETS.iter().all(|&o| o < 64));
    }

    #[test]
    fn pi_lane_indices_is_permutation() {
        // π is a permutation of {0..25}.
        assert_eq!(PI_LANE_INDICES.len(), 25);
        let mut sorted: Vec<usize> = PI_LANE_INDICES.to_vec();
        sorted.sort();
        for i in 0..25 {
            assert_eq!(sorted[i], i, "PI_LANE_INDICES is not a permutation");
        }
    }

    #[test]
    fn round_step_count() {
        assert_eq!(RoundStep::ALL.len(), 5);
    }

    #[test]
    fn absorb_layout_row_budget() {
        let l = AbsorbAirLayout::new(Sha3Variant::Sha3_384, 4);
        assert_eq!(l.rows_per_permutation, 120);  // 24 × 5
        assert_eq!(l.rows_per_absorb_block, 121); // 120 + XOR row
        assert_eq!(l.total_rows(), 121 * 4);
        // Width sanity: 1600 state bits + 4×25 helper lanes + 1 RC + 5 selectors.
        assert_eq!(l.width, 1600 + 100 + 1 + 5);
    }

    #[test]
    fn absorb_layout_scales_linearly_with_blocks() {
        let l1 = AbsorbAirLayout::new(Sha3Variant::Sha3_256, 1);
        let l4 = AbsorbAirLayout::new(Sha3Variant::Sha3_256, 4);
        assert_eq!(l4.total_rows(), 4 * l1.total_rows());
        // Width is independent of block count.
        assert_eq!(l4.width, l1.width);
    }

    #[test]
    #[should_panic(expected = "not yet wired")]
    fn keccak_f1600_stub_panics() {
        let mut s: KeccakState = [0; 25];
        keccak_f1600(&mut s);
    }

    #[test]
    #[should_panic(expected = "unsupported NIST level")]
    fn sha3_variant_rejects_invalid_level() {
        let _ = Sha3Variant::default_for_level(2);
    }
}
