#!/usr/bin/env bash
# Aggregate per-AIR CSVs into:
#   - results/summary.csv          : every per-run row, concatenated
#   - results/summary_median.csv   : 3-run medians by
#                                    (air, level, hash, r, n_trace, blowup, ldt)
#   - results/paper_table_single.tex : LaTeX drop-in for Table 6
#                                      (single-AIR scaling rows)
#   - results/paper_table_crypto.tex : LaTeX drop-in for Table 7
#                                      (real cryptographic AIRs)
#
# The two-table split mirrors the post-2026-05-09 paper layout:
# single AIRs (Fibonacci / PoseidonChain / RegisterMachine / cairo-*)
# go in Table~\ref{tab:benchmarks}; cryptographic AIRs (rsa2048-verify,
# mldsa-v2-verify, ed25519-verify-*) go in Table~\ref{tab:crypto-airs}.

set -euo pipefail
cd "$(dirname "$0")"
SCRIPT_DIR="$(pwd)"
RESULTS_DIR="$SCRIPT_DIR/results"

cd "$RESULTS_DIR"

# ─── 1. Concatenate all per-AIR CSVs ────────────────────────────
SUMMARY_CSV="summary.csv"
HEADER="air,level,ext_field,hash,r,n_trace,blowup,prove_ms,verify_ms,proof_kib,peak_rss_mib,run_idx,ldt"
echo "$HEADER" > "$SUMMARY_CSV"

for f in cairo-suite.csv simple-scaling.csv hash-rollup.csv \
         ed25519.csv rsa2048.csv \
         mldsa-l1.csv mldsa-l3.csv mldsa-l5.csv; do
    if [ -f "$f" ]; then
        tail -n +2 "$f" >> "$SUMMARY_CSV"
    fi
done

# ─── 2. Median of triplicate runs ───────────────────────────────
# Group by (air, level, ext, hash, r, n_trace, blowup, ldt) — n_trace
# is in the key so simple-AIR scaling sweeps don't collapse rows.
MEDIAN_CSV="summary_median.csv"
echo "air,level,ext_field,hash,r,n_trace,blowup,prove_ms,verify_ms,proof_kib,n_runs,ldt" \
    > "$MEDIAN_CSV"

awk -F, '
    NR == 1 { next }
    {
        # Stable composite key: air,level,ext,hash,r,n_trace,blowup,ldt
        k = $1 "," $2 "," $3 "," $4 "," $5 "," $6 "," $7 "," $13
        prove[k]  = prove[k]  " " $8
        verify[k] = verify[k] " " $9
        size[k]   = size[k]   " " $10
        cnt[k]++
    }
    # Portable median (BSD awk has no asort).  Bubble sort on the
    # short list of run measurements; n is typically 3.
    function median(s,    a, n, i, j, t) {
        n = split(s, a, " ")
        for (i = 1; i <= n; i++) a[i] = a[i] + 0
        for (i = 1; i < n; i++) {
            for (j = 1; j <= n - i; j++) {
                if (a[j] > a[j+1]) {
                    t = a[j]; a[j] = a[j+1]; a[j+1] = t
                }
            }
        }
        return a[int((n + 1) / 2)]
    }
    END {
        for (k in prove) {
            pm = median(prove[k])
            vm = median(verify[k])
            zm = median(size[k])
            printf "%s,%.0f,%.2f,%.1f,%d\n", k, pm, vm, zm, cnt[k]
        }
    }
' "$SUMMARY_CSV" | sort >> "$MEDIAN_CSV"

# ─── 3a. LaTeX fragment — Table 6 (single AIRs) ─────────────────
SINGLE_TEX="paper_table_single.tex"
{
    echo "% Auto-generated by scripts/aws-bench/aggregate.sh"
    echo "% Drop-in replacement for the tabular block in"
    echo "% main-22.tex Table~\\ref{tab:benchmarks} (single-AIR scaling)."
    echo "\\begin{tabular}{l c c l r r r r r}"
    echo "\\toprule"
    echo "AIR & Level & Ext.\\ & Hash & \$r\$ & \$T\$ & Proof & \$t_\\mathrm{verify}\$ & \$t_\\mathrm{prove}\$ \\\\"
    echo "    &       &       &      &     &       & (KiB) & (ms)                    & (s)                   \\\\"
    echo "\\midrule"
} > "$SINGLE_TEX"

awk -F, '
    NR == 1 { next }
    # Single-AIR rows.  MEDIAN_CSV columns:
    #   1=air 2=level 3=ext 4=hash 5=r 6=n_trace 7=blowup 8=ldt
    #   9=prove_ms 10=verify_ms 11=proof_kib 12=n_runs
    $1 ~ /^(Fibonacci|PoseidonChain|RegisterMachine|CairoSimple|cairo-|hash-rollup|simple-)/ {
        air = $1; level = $2; ext = $3; hash = $4; r = $5
        n_trace = $6 + 0
        prove_ms  = $9  + 0
        verify_ms = $10 + 0
        proof_kib = $11 + 0
        prove_s   = prove_ms / 1000.0
        t_repr = (n_trace > 0 && (log(n_trace)/log(2)) == int(log(n_trace)/log(2))) \
                  ? sprintf("$2^{%d}$", int(log(n_trace)/log(2))) \
                  : sprintf("%d", n_trace)
        # Sort key: (air, level, hash, n_trace) — pad n_trace to 12
        # digits so lexicographic sort = numeric sort.
        printf "%s|%s|%s|%012d\t%-22s & %s & $\\mathbb{F}_{p^%s}$ & \\texttt{%s} & %3d & %s & %.0f & %.1f & %.2f \\\\\n",
            air, level, hash, n_trace,
            air, level, substr(ext, 3), hash, r, t_repr, proof_kib, verify_ms, prove_s
    }
' "$MEDIAN_CSV" | sort -t $'\t' -k1,1 | cut -f2- >> "$SINGLE_TEX"

{
    echo "\\bottomrule"
    echo "\\end{tabular}"
} >> "$SINGLE_TEX"

# ─── 3b. LaTeX fragment — Table 7 (cryptographic AIRs) ──────────
# Cryptographic AIR proofs are 0.7--67 MiB; convert KiB → MiB (1 dp).
CRYPTO_TEX="paper_table_crypto.tex"
{
    echo "% Auto-generated by scripts/aws-bench/aggregate.sh"
    echo "% Drop-in replacement for the tabular block in"
    echo "% main-22.tex Table~\\ref{tab:crypto-airs} (real cryptographic AIRs)."
    echo "\\begin{tabular}{l c l r r r r}"
    echo "\\toprule"
    echo "AIR & Level & Hash & \$r\$ & Proof & \$t_\\mathrm{verify}\$ & \$t_\\mathrm{prove}\$ \\\\"
    echo "    &       &      &     & (MiB) & (ms)                    & (s)                   \\\\"
    echo "\\midrule"
} > "$CRYPTO_TEX"

awk -F, '
    NR == 1 { next }
    # Same column layout as the single-AIR awk above.
    $1 ~ /^(rsa2048-verify|mldsa-v2-verify|ed25519-verify)/ {
        air = $1; level = $2; ext = $3; hash = $4; r = $5
        prove_ms  = $9  + 0
        verify_ms = $10 + 0
        proof_kib = $11 + 0
        prove_s   = prove_ms / 1000.0
        proof_mib = proof_kib / 1024.0
        # Friendly AIR labels.
        label = air
        if (air == "rsa2048-verify")   label = "RSA-2048 verify"
        if (air == "mldsa-v2-verify") {
            if (level == "L1") label = "ML-DSA-44 verify v2"
            if (level == "L3") label = "ML-DSA-65 verify v2"
            if (level == "L5") label = "ML-DSA-87 verify v2"
        }
        if (air == "ed25519-verify-v16") label = "Ed25519 verify (v16)"
        printf "%-24s & %s & \\texttt{%s} & %3d & %5.2f & %.1f & %.1f \\\\\n",
            label, level, hash, r, proof_mib, verify_ms, prove_s
    }
' "$MEDIAN_CSV" >> "$CRYPTO_TEX"

{
    echo "\\bottomrule"
    echo "\\end{tabular}"
} >> "$CRYPTO_TEX"

# ─── 4. Status report ───────────────────────────────────────────
echo "[aggregate] wrote:"
echo "  $SUMMARY_CSV"
echo "  $MEDIAN_CSV"
echo "  $SINGLE_TEX     → paste into Table~\\ref{tab:benchmarks}"
echo "  $CRYPTO_TEX     → paste into Table~\\ref{tab:crypto-airs}"
