#!/usr/bin/env bash
# Aggregate per-AIR CSVs into:
#   - results/summary.csv : one row per (air, level), median of runs
#   - results/paper_table.tex : LaTeX-friendly drop-in for paper Table 6

set -euo pipefail
cd "$(dirname "$0")"
SCRIPT_DIR="$(pwd)"
RESULTS_DIR="$SCRIPT_DIR/results"

cd "$RESULTS_DIR"

# ─── 1. Concatenate all CSVs ────────────────────────────────────
SUMMARY_CSV="summary.csv"
HEADER="air,level,ext_field,hash,r,n_trace,blowup,prove_ms,verify_ms,proof_kib,peak_rss_mib,run_idx,ldt"
echo "$HEADER" > "$SUMMARY_CSV"

for f in cairo-suite.csv hash-rollup.csv ed25519.csv rsa2048.csv \
         mldsa-l1.csv mldsa-l3.csv mldsa-l5.csv; do
    if [ -f "$f" ]; then
        # skip individual headers
        tail -n +2 "$f" >> "$SUMMARY_CSV"
    fi
done

# ─── 2. Median of triplicate runs per (air, level, blowup, ldt) ─
MEDIAN_CSV="summary_median.csv"
echo "air,level,ext_field,hash,r,blowup,prove_ms,verify_ms,proof_kib,n_runs,ldt" \
    > "$MEDIAN_CSV"

# Group by (air, level, blowup, ldt) and take median of prove/verify/size.
# Done in awk for portability (no Python required on AWS image).
awk -F, '
    NR == 1 { next }
    {
        k = $1 "," $2 "," $3 "," $4 "," $5 "," $7 "," $13
        prove[k] = prove[k] " " $8
        verify[k] = verify[k] " " $9
        size[k] = size[k] " " $10
        cnt[k]++
    }
    END {
        for (k in prove) {
            n = split(prove[k], pa, " "); delete sa
            for (i = 1; i <= n; i++) sa[i] = pa[i] + 0
            asort(sa)
            mid = int((n + 1) / 2)
            pm = sa[mid]

            n = split(verify[k], pa, " "); delete sa
            for (i = 1; i <= n; i++) sa[i] = pa[i] + 0
            asort(sa)
            vm = sa[int((n + 1) / 2)]

            n = split(size[k], pa, " "); delete sa
            for (i = 1; i <= n; i++) sa[i] = pa[i] + 0
            asort(sa)
            zm = sa[int((n + 1) / 2)]

            printf "%s,%.0f,%.2f,%.1f,%d\n", k, pm, vm, zm, cnt[k]
        }
    }
' "$SUMMARY_CSV" | sort >> "$MEDIAN_CSV"

# ─── 3. LaTeX table fragment ────────────────────────────────────
PAPER_TEX="paper_table.tex"
{
    echo "% Auto-generated by scripts/aws-bench/aggregate.sh"
    echo "% Drop-in replacement for the tabular block in main-22.tex Table 6."
    echo "\\begin{tabular}{l c l r r r r r}"
    echo "\\toprule"
    echo "AIR & Level & Ext.\\ & Hash & \$r\$ & Proof (KiB) & \$t_\\mathrm{verify}\$ (ms) & \$t_\\mathrm{prove}\$ (s) \\\\"
    echo "\\midrule"
} > "$PAPER_TEX"

awk -F, '
    NR == 1 { next }
    {
        air = $1; level = $2; ext = $3; hash = $4; r = $5
        prove_ms = $7; verify_ms = $8; proof_kib = $9
        prove_s = prove_ms / 1000.0
        printf "%-30s & %s & $\\mathbb{F}_{p^%s}$ & \\texttt{%s} & %3d & %.0f & %.1f & %.2f \\\\\n",
            air, level, substr(ext, 3), hash, r, proof_kib, verify_ms, prove_s
    }
' "$MEDIAN_CSV" >> "$PAPER_TEX"

{
    echo "\\bottomrule"
    echo "\\end{tabular}"
} >> "$PAPER_TEX"

echo "[aggregate] wrote $SUMMARY_CSV, $MEDIAN_CSV, $PAPER_TEX"
echo "[aggregate] paste $PAPER_TEX into main-22.tex Table 6 \\begin{tabular}{...} block."
